### ISSUE TITLE
pattern.search sometimes aborts due to type difference under Unix-Like Systems

### ISSUE THREAD

**Issue by ermueller** [blosloos/nontarget#2]
Hi,

I found a bug in pattern.search where memory allocation sometimes goes wrong under unix-like systems. I don't know if this bug occurs under windows, but it does under Max and Linux.

Sometimes the function tries to allocate up to 80GB of RAM to a single variable, and - naturally - the program stops, because it can't allocate that much memory.

[In pattern.search.R on line 99](https://github.com/blosloos/nontarget/blob/1e9b6c8/R/pattern.search.R#L99) an integer is passed as the third argument to the [mass function in massCpp.cpp](https://github.com/blosloos/nontarget/blob/1e9b6c8215365d749a7daa2a226540f34d56af2d/src/massCpp.cpp)

The third argument of that C-Function, however, is of [type size_t](https://github.com/blosloos/nontarget/blob/1e9b6c8215365d749a7daa2a226540f34d56af2d/src/massCpp.cpp#L24)

Since this issue goes very deep into communication between C and R and the memory management, I don't 100% know what is going on - all I know is that it (only sometimes, for some peculiar reason) results in the C-code interpreting the number as *far* too big, maybe because of a wrong variable byte size allocation?

It's very weird, since it just happens *sometimes* and other times it doesn't, even when using the exact same input, so I sadly can't even give a reproducible example. Though it can happen with *any* input, as far as I can tell.

Changing the the type of `size_t *a` to `int *a` solves the problem and I haven't had it happen since. It starts happening again when I change it back, so I'm relatively certain that this is the cause.

I know that this isn't a *clean* solution, since `a` denotes an object size and not just any integer value, but you probably know more about the Rcpp interface to solve this problem the right way.

**Comment by blosloos** [comment]
Dear ermueller

Thanks for your detailed feedback. Have changed size_t in any .C calls to integer pointers, as suggested (please install nontarget form github for the time being). Strange, never had a problem on windows with this. Am not testing much on Mac or Linux OS, but there different compilers produce other problems as compared to those faced on Windows. With the somewhat poor R-side documentation of SEXP memory assignment, I assumed that size_t would be the right thing to use instead of an integer - obviouly it is not. size_t can lead to overflows when used in this context?
